Music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from Music.views import *

app_name='Music'

urlpatterns = [
    url(r'^$', SongsList.as_view(), name='music'),
    url(r'^(?P<curr>[0-9]*)$', SongsList.as_view(), name='music'),
    url(r'^update/', updateSongs, name='updateSongs'),
    url(r'^record/$', record, name='record'),
    url(r'^add/$', AddSong, name='add'),  # needs improvement
    # url(r'^test/$', test, name='test'),  # needs improvement
    # url(r'^test/$', cfList ,name='test'),

]

RecSys/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls ),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^Music/', include('Music.urls')),
    url(r'^$', index, name='index'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT}))

accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import LoginView,LogoutView
from .views import SignUp, ProfileView, LoginView, LogoutView, DashboardView
from django.contrib.auth.decorators import login_required

app_name='accounts'
urlpatterns = [
    url(r'^signup/$',SignUp.as_view(),name='signup'),
    url(r'^profile/(?P<pk>\d+)$',ProfileView.as_view(),name='profile'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$',login_required(DashboardView.as_view()),name='dashboard'),

]

Music/models.py
from django.db import models
from accounts.models import User
# Create your models here.
class Song(models.Model):
	song_id = models.AutoField(primary_key=True)
	song_name = models.CharField(max_length=200,blank=True)
	song_file = models.FileField(upload_to='music',blank=True,null=True)
	# song_url = models.URLField(blank=True)
	# release_date = models.DateField('date released', null=True,blank=True)
	added_on = models.DateField('date added',auto_now_add=True,null=True,blank=True)
	# artist = models.CharField(max_length=100, blank=True)
	# album = models.CharField(max_length=100, blank=True)
	# genre = models.CharField(max_length=100, blank=True)
	# country = models.CharField(max_length=100, blank=True)
	readonly_fields=('song_id')
	user_id = models.ForeignKey(User,blank=True, null=True)

	def attrs(self):
		for field in self._meta.fields:
			yield field.name, getattr(self, field.name)

	def __str__(self):
		return self.song_name

class Record(models.Model):
	record_id = models.AutoField(primary_key=True)
	song_id = models.ForeignKey(Song,related_name='current_song')
	user_id = models.ForeignKey(User)
	song_name = models.CharField(max_length=200)
	next_song = models.ForeignKey(Song,related_name='next_song', blank=True, null=True)
	percent_played = models.IntegerField(default=0)

	listen_date = models.DateTimeField(auto_now_add=True)
	
	def attrs(self):
		for field in self._meta.fields:
			yield field.name, getattr(self, field.name)

	def __str__(self):
		return str(self.user_id)+" " + str(self.song_id)+" "+self.song_name 

Music/forms.py
from django.forms.models import ModelForm
from django import forms
from .models import Song

class AddSongForm(forms.Form):
	song_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'plceholder':'File Name'}))
	song_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder':'Song Name'}))

	# def clean(self):
		# raise Exception(self.request)

	# class Meta:
		# model = Song
		# exclude = ('added_on','user_id',)

Music/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .models import Song, Record
from .forms import AddSongForm
# Create your views here.

class SongsList(ListView):
	model = Song
	template_name = 'Music/index2.html'

	def get_context_data(self, **kwargs):
		# user = request.user
		# raise Exception('curr' not in self.kwargs)
		context = super().get_context_data(**kwargs)
		context['popular'] = self.popularList(**kwargs)
		if self.request.user.is_authenticated:
			context['cf'] = self.cfList(**kwargs)
			context['ocf'] = self.ocfList(**kwargs)
		if 'curr' not in self.kwargs:
			if self.request.user.is_authenticated:
				if 'cf' in context :
					context['curr'] = context['cf'][0]
				else:
					context['curr'] = None

			else :
				if 'popular' in context :
					context['curr'] = context['popular'][0]
				else:
					context['curr'] = None
		else:
			context['curr'] = Song.objects.get(pk=self.kwargs['curr'])
		# raise Exception(type(context['curr']))
		return context

	def popularList(self,**kwargs):
		# function to return most popular songs based on listen count 
		# from Music.models import Song,Record
		# raise Exception ( self.kwargs['curr'])
		if 'curr' not in self.kwargs:
			songs = Song.objects.all()
		else :
			songs = Song.objects.exclude(pk__exact=self.kwargs['curr'])
		songs_list = [x for x in songs]
		count = [[songs_list.index(x),0] for x in songs]
		# dic = { x:0 for x in songs}
		# raise Exception(dic)
		if 'curr' not in self.kwargs:
			records = Record.objects.all()
		else:
			records = Record.objects.exclude(song_id__exact=self.kwargs['curr'])
		for x in records:
			count[songs_list.index(x.song_id)][1] = count[songs_list.index(x.song_id)][1]+1
		

		import operator
		sorted_dic = sorted(count, key=operator.itemgetter(1), reverse=True)
		
		# raise Exception(sorted_dic)
		lst = [ songs_list[x[0]]  for x in sorted_dic  ]
		from django.core import serializers
		data = serializers.serialize('json', lst[:10], fields=('song_id','song_name'))
		return lst
		# return HttpResponse( data )#JsonResponse(lst,safe=False) )



	def cfList(self,**kwargs):
		# not working properly 
		# predicts completely random songs
		# maybe more training data is required
		from django.contrib.auth import get_user_model
		import numpy as np
		if 'curr' not in self.kwargs:
			songs_list = [x for x in Song.objects.all()]
		else:
			songs_list = [x for x in Song.objects.exclude(pk__exact=self.kwargs['curr'])]
		users_list = [x for x in get_user_model().objects.all()]
		is_rated = lambda s,u: Record.objects.filter(song_id=s,user_id=u).exists()
		np_rated = np.array([ [ is_rated(s,u)  for u in users_list] for s in songs_list] )
		np_cfmat = np.array([ [rate(s,u) for u in users_list] for s in songs_list] ) # rate function calculates the rating using history of each user
		# raise Exception(np_cfmat)
		
		# ---------------------------------------------------------------- 

		# from sklearn.metrics.pairwise import pairwise_distances as dist
		# user_similarity = dist(np_cfmat, metric='cosine')
		# item_similarity = dist(np_cfmat.T, metric='cosine')
		# raise Exception(user_similarity)

		# ---------------------------------------------------------------- 
		

		num_features = 5
		features = np.random.randn(len(songs_list),num_features)
		# raise Exception(features)
		theta = np.random.randn(len(users_list),num_features)
		theta, features = grad(np_rated, np_cfmat, songs_list, users_list, theta, features)
		
		user = self.request.user
		index = users_list.index(user)
		predicted_ratings = np.dot(features,theta[index].T)
		# raise Exception((predicted_ratings))
		i=0
		lst = [ [x,y] for x,y in zip(predicted_ratings,songs_list)]
		# raise Exception(lst)
		lst = sorted(lst,reverse=True)
		# raise Exception(lst)
		songs_lst = [s for rating,s in lst]
		return songs_lst

		# raise Exception(songs)
		from django.core import serializers
		data = serializers.serialize('json', songs, fields=('song_id','song_name'))
		# raise Exception(dic)
		return HttpResponse(data )	


	def ocfList(self,**kwargs):
		# from Music.models import Song,Record
		if 'curr' not in self.kwargs:
			return Song.objects.all()[:10]
		else:
			return Song.objects.exclude(pk__exact=self.kwargs['curr'])[:10]
		from django.core import serializers
		data = serializers.serialize('json', Song.objects.all()[:10], fields=('song_id','song_name'))
		# raise Exception(dic)
		return HttpResponse(data )

@login_required
def AddSong(request):
	if request.method == "POST" :
		NewSongForm = AddSongForm(request.POST, request.FILES)

		if NewSongForm.is_valid():
			newsong = Song()
			newsong.song_name = NewSongForm.cleaned_data['song_name']
			newsong.song_file = NewSongForm.cleaned_data['song_file']
			newsong.user_id = request.user
			newsong.save()
	else:
		form = AddSongForm()

	return render(request, 'Music/song_form.html', locals())

def index(request):
	# return render(request, 'Music/index.html' )
	return HttpResponse("inside Music(RecSys)")

def updateSongs(request):
	param = request.GET.get('q','')
	if(param=="optimised"):
		return optimisedList(request=request)
	elif(param == "cf"):
		return cfList(request=request)
	else :
		return popularList(request=request)
	

def saveNewSongs(request):
	import os
	BASE_DIR = os.path.dirname(os.path.dirname(__file__))
	# return HttpResponse("inside Music(trendy)")
	files = os.listdir(os.path.join(BASE_DIR, "static/Music/Songs/"))
	#dic = { str(x):x for x in files}
	count=0
	from Music.models import Song
	for x in files:
		if(Song.objects.filter(song_name=x).count()==0):
			s = Song(song_name=x)
			s.save()
			count=count+1
		else:
			pass
			# raise Exception(x)
	# raise Exception(dic)
	return HttpResponse("recorded "+str(count)+" songs" )


def record(request):
	if 'song_id' in request.POST and 'per' in request.POST and 'next_song' in request.POST:
		# from Music.models import Record,Song
		# from login.models import User
		s = Song.objects.get(song_id=request.POST['song_id'])
		next_song = Song.objects.get(song_id=request.POST['next_song'])
		from accounts.models import User
		u = User.objects.get(pk=request.user.pk)
		r = Record(song_id=s, user_id=u, song_name=s.song_name,next_song=next_song,percent_played=float(request.POST['per']) )
		r.save()
		# return HttpResponse("all found")
	else :
		return HttpResponse("Invalid Data")

	return HttpResponse("recorded "+str(s) )

def suggestNext(request):
	if 'user' in request:
		# User Specific Suggestion for next Song
		return HttpResponse("Suggestions coming soon..." )
	else:
		# Popularity based Suggestion for next song 
		return HttpResponse("Personalised Suggestions coming soon..." )



def rate(s,u):
	""" Function to give rating to songs based on previous history of the user """
	from Music.models import Record
	# unknown_song = True
	rating = 0
	count = 0
	for r in Record.objects.filter(user_id=u,song_id=s):
		count = count + 1;
		rating = rating + r.percent_played/100
		# unknown_song=False

	# if(unknown_song == True):
		# return -1
	# else:
	if(count==0):
		return 0
	else:
		return (rating / count)

def grad(np_rated, np_cfmat, songs_list, users_list, theta, features):
	""" Function for gradient descent used in Collaborative filtering """

	import numpy as np
	alpha = 0.5
	# raise Exception(theta.shape[1])
	for k in range(theta.shape[1]):
		# print(k)
		del_x = 0
		del_t = 0
		for i in range(len(songs_list)):
			for j in range(len(users_list)):
				if(np_rated[i][j]):
					del_x = del_x + (np.dot(features[i],theta[j].T) - np_cfmat[i][j]) * features[i][k] 
					del_t = del_t + (np.dot(features[i],theta[j].T) - np_cfmat[i][j]) * theta[j][k] 
		features[:,k] = features[:,k] - alpha * del_x
		theta[:,k] = theta[:,k] - alpha * del_t
		# raise Exception(features[:][0])
	# raise Exception(theta)
	return (theta, features)

Music/templates/Music/index.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}
{% load staticfiles %}
{% load static %}
<script type="text/javascript" src="{% static 'trendy/js/jquery.min.js' %}"></script>
{% csrf_token %}
<script> 
var csrftoken = $('input[name=csrfmiddlewaretoken]').attr('value');
$( document ).ready(function() {
    // console.log(csrftoken);
    $(window).load(function(){
          fetchResults('popular', 'popular');
          fetchResults('cf', 'cf');
          fetchResults('optimised', 'optimised');

    });
    function fetchResults(type, div){
          var url = 'update/?q='+type;
          div = "."+div;

          var data = { 'csrfmiddlewaretoken' : csrftoken}
          
          $.post( url, data)
          .done(function( data ) {
            var src_path="{% static 'Music/Songs/' %}";
            var json = $.parseJSON(data);
            $.each(json, function(key,obj){
              // obj format {model:"Music.song", pk:"<pk>", fields:{song_name:"<song_name>"}}
              // console.log(obj.fields);
              var src = src_path + obj.fields.song_name;
              var s = "<div class=\"song\" value='"+src+"' song_id=\""+obj.pk+"\">"+obj.pk+" <b>"+obj.fields.song_name+"</b></div><br>";
              // var s="<audio controls><source src='" +src+ "' type='audio/mpeg'>Your browser does not support the audio element.</audio>"+obj+"<br>";
              $( div ).append( s );
              // console.log(s);
              // console.log(obj);
            });
            
          });
    }

    $(".result").on("click",".song",function(){
      var src = $(this).attr('value');
      var song_id = $(this).attr('song_id');
      record(song_id);
      // alert(song_id);
      // var src= "asd";
      // alert("asd");
      console.log(" playing id="+song_id);
        var s = "<audio class=\"audiotrack\"controls=\"controls\" autoplay=\"true\"><source src='" +src+ "' type='audio/mpeg' song_id='"+song_id+"'>Your browser does not support the audio element.</audio><br>";
        $(".player").html(s);
    });

    console.log( "ready!" );
    $( window ).unload(function() {
      record(); 
    });
});

function record(next_song){
    var csrftoken = $('input[name=csrfmiddlewaretoken]').attr('value');
    // console.log(csrftoken);
    var url = 'record/';
    var song_id = $('source' ).attr('song_id');
    // var per=100;
    var per = ($(".audiotrack").prop("currentTime") / $("audio")[0].duration)*100;
    // alert(per);
    var data = { 'csrfmiddlewaretoken' : csrftoken, 'song_id':song_id, 'per':per, 'next_song':next_song}
    // console.log(data);
    $.post( url, data).done(function(data){console.log(data);});

}

</script>
<div class="row">
  
  <div class="popular result col l4 m4 s12">
  <h5>Popular Songs:</h5><br>
  </div>
  <div class="cf result col l4 m4 s12">
  <h5>Colaborative Filtering:</h5><br>
  </div>
  <div class="optimised result col l4 m4 s12">
  <h5>Optimised CF:</h5><br>
  </div>

  
</div>

<div class="player" style="display:block;position:fixed;bottom:0px;width:100%;height:auto;">
<audio class="audiotrack" controls="controls" autoplay="true"><source src="" type='audio/mpeg' song_id="">Your browser does not support the audio element.</audio><br>
</div>

<style>
.player audio{
  background:red;
  height:auto;
  width:100%;
}

</style>

{% endblock %}

Music/templates/Music/index2.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Music/musiccss.css' %}"></script>
{% csrf_token %}
<div class ="section row">
    <div class="col m4 l4 s12">
      {% block SuggestedSongs %} 
        <div class="row ">
            
            <div class="cf result col l6 m6 s12">
                {% if user.is_authenticated %}
                  {% if cf %}
                    <table class="bordered highlight centered ">
                    <thead><tr><th>Colaborative Filtering:</th></tr></thead>
                    <tbody>
                      {%for song in cf %}
                          <tr>
                          <td><div class="song" value='{{song.song_file.url}}' song_id="{{song.pk}}">   {{song.song_name}}</div></td>
                          </tr>
                      {%endfor%}
                    </tbody>
                    </table>
                    
                  {% else %}
                      <b>No suggestion for you :-( <b>
                  {% endif %}

                {% else %}
                  <b><a href = "{%url 'accounts:login' %}" >Log In </a> for personalised suggestions</b>
                <!-- 
                <div class="optimised result col l4 m4 s12">
                <h5>Optimised CF:</h5><br>
                {%for song in ocf %}
                    <div class="song" value='{{song.song_file.url}}' song_id="{{song.pk}}"> <b>{{song.song_name}}</b></div><br>
                {%endfor%}
                </div>
                 -->
                {% endif %}
            </div>


            <div class="popular result col l6 m6 s12">
            
            {% if popular %}
             
            <table class="bordered highlight centered ">
            <thead><tr><th>Popular Songs:</th></tr></thead>
            <tbody>
              {%for song in popular %}
                  <tr>
                  <td><div class="song" value='{{song.song_file.url}}' song_id="{{song.pk}}">   {{song.song_name}}</div></td>
                  </tr>
              {%endfor%}
            </tbody>
            </table>
            {% else %}
              <b>Nothing is popular in this country :-(</b>
            {% endif %}
            </div>
            
          </div>
          {% endblock %}
    </div>
    <div class="col result m2 l2 s12">
    {% block AllSongs %}
      {% if object_list %}
      <table class="bordered highlight centered ">
      <thead><tr><th>All Songs:</th></tr></thead>
      <tbody>
        {%for song in object_list %}
            <tr>
            <td><div class="song" value='{{song.song_file.url}}' song_id="{{song.pk}}">   {{song.song_name}}</div></td>
            </tr>
        {%endfor%}
      </tbody>
      </table>
      
      {% else %}
          <b>This world is running out of Good Music :-P </b>
      {% endif %}
      {% endblock %}
    </div>
    <div class="col m6 l6 s12">
        {% block CurrentSong %}
        <div class= "row">
          
              <div class="card white darken-1 details large">
                {% if not curr %}
                  <div class='error'>Nothing To Play Come Back Later...</div>
                {% else %}

                <div class="card-content ">
                  <span class="card-title center" style="font-size:3em;margin:20px;">{{curr.song_name}}</span>
                  <table class="centered responsive-table">
                    <thead>
                    <tr>
                      {% for key, val in curr.attrs %}
                        <th >{{key}}</th>
                      {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    <tr >
                      {% for key, val in curr.attrs %}
                        <td ><small>{{val}}</small></td>
                      {% endfor %}
                    </tr>
                    </tbody>
                    </table>
                    
                </div>
                <div class="card-action">
                  <a href="#">Currently Playing...</a>
                </div>
                {% endif %}
              </div>
        </div>
        {% endblock %}
        
    </div>
    
</div>  

<a class="btn-floating btn-large waves-effect waves-light red" style="position:fixed;bottom:10%;right:2%;" href="{% url 'Music:add' %}"><i class="material-icons">add</i></a>

<div class="player row">
<div class="col l1 m4 s12">
<span>{{curr}} </span>
</div>
<div class="col l11 m8 s12">
<audio class="audiotrack" controls="controls" autoplay="true">
<source src="{{curr.song_file.url}}" type='audio/mpeg' song_id="{{curr.song_id}}" next_song_id="{% if not cf %}{{object_list.first.song_id}}{%else%}{{cf.0.song_id}}{%endif%}">
Your browser does not support the audio element.</audio><br>
</div>
</div>

<script type="text/javascript" src="{% static 'Music/musicjs.js' %}"></script>

{% endblock %}

Music/templates/Music/song_form.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}

<div class="row container valign-wrapper" style="margin-top:10%;">

<div class="col m4 l4 s12">

<h3><blockquote class="green-text">Add Song</blockquote></h3>
</div>
<br>

<div class="col m8 l8 s12">

<form name='form' method="POST" action = "{% url 'Music:add' %}?next={{next}}" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}

<br>
  <button class="btn blue darken-4 waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
        
</form>
</div>
</div>
{%endblock%}