Music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from Music.views import *

app_name='Music'

urlpatterns = [
    url(r'^$', SongsList.as_view(), name='music'),
    url(r'^(?P<curr>[0-9]*)$', SongsList.as_view(), name='music'),
    url(r'^update/', updateSongs, name='updateSongs'),
    url(r'^record/$', record, name='record'),
    url(r'^add/$', AddSong, name='add'),  # needs improvement
    # url(r'^test/$', test, name='test'),  # needs improvement
    # url(r'^test/$', cfList ,name='test'),

]

RecSys/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls ),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^Music/', include('Music.urls')),
    url(r'^$', index, name='index'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT}))

accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import LoginView,LogoutView
from .views import SignUp, ProfileView, LoginView, LogoutView, DashboardView
from django.contrib.auth.decorators import login_required

app_name='accounts'
urlpatterns = [
    url(r'^signup/$',SignUp.as_view(),name='signup'),
    url(r'^profile/(?P<pk>\d+)$',ProfileView.as_view(),name='profile'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$',login_required(DashboardView.as_view()),name='dashboard'),

]

Music/models.py
from django.db import models
from accounts.models import User
# Create your models here.
class Song(models.Model):
	song_id = models.AutoField(primary_key=True)
	song_name = models.CharField(max_length=200,blank=True)
	song_file = models.FileField(upload_to='music',blank=True,null=True)
	# song_url = models.URLField(blank=True)
	# release_date = models.DateField('date released', null=True,blank=True)
	added_on = models.DateField('date added',auto_now_add=True,null=True,blank=True)
	# artist = models.CharField(max_length=100, blank=True)
	# album = models.CharField(max_length=100, blank=True)
	# genre = models.CharField(max_length=100, blank=True)
	# country = models.CharField(max_length=100, blank=True)
	readonly_fields=('song_id')
	user_id = models.ForeignKey(User,blank=True, null=True)

	def attrs(self):
		for field in self._meta.fields:
			yield field.name, getattr(self, field.name)

	def __str__(self):
		return self.song_name

class Record(models.Model):
	record_id = models.AutoField(primary_key=True)
	song_id = models.ForeignKey(Song,related_name='current_song')
	user_id = models.ForeignKey(User)
	song_name = models.CharField(max_length=200)
	next_song = models.ForeignKey(Song,related_name='next_song', blank=True, null=True)
	percent_played = models.IntegerField(default=0)

	listen_date = models.DateTimeField(auto_now_add=True)
	
	def attrs(self):
		for field in self._meta.fields:
			yield field.name, getattr(self, field.name)

	def __str__(self):
		return str(self.user_id)+" " + str(self.song_id)+" "+self.song_name 

accounts/models.py
from django.db import models
from django.contrib.auth import models 
# Create your models here.

class User(models.AbstractUser):
	
	def attrs(self):
		for field in self._meta.fields:
			yield field.name, getattr(self, field.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class SignUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username',)

class LoginForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username','password',)

accounts/views.py
from django.shortcuts import render, redirect, resolve_url
# from django import forms
from django.views.generic.edit import FormView
from django.views.generic import DetailView, TemplateView
from django.views import View
# from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse_lazy
from .models import User
from .forms import SignUpForm, LoginForm
from django.shortcuts import redirect, reverse
from django.contrib.auth.views import LoginView as Login,LogoutView as Logout

class SignUp(FormView):
	template_name = 'accounts/signup.html'
	form_class = SignUpForm
	success_url = reverse_lazy('accounts:login')
	redirect_authenticated_user = True
	def get(self, request):
		if request.user.is_authenticated:
			return redirect(reverse('accounts:dashboard'))
		return super().get(request)

	def form_valid(self, form):
		form.save()
		return super(SignUp, self).form_valid(form)

class LoginView(Login):
	template_name = 'registration/login.html'
	redirect_authenticated_user = True
	# form_class = LoginForm
	# def post(self,request, **kwargs):
	# 	form = self.form_class(request.POST)
	# 	if form.is_valid():
			
	# 		raise Exception(form)
	
	def get_success_url(self):
		# url = super().get_redirect_url()
		redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
		# raise Exception(self.get_redirect_url() )
		return redirect_to or reverse_lazy('accounts:dashboard')

class LogoutView(Logout):
	pass

class ProfileView(DetailView):
	model = User
	# self.pk = self.request.user.pk


class DashboardView(TemplateView):
	template_name = 'accounts/dashboard.html';
	# def get(self, request):
	# 	context = self.get_context_data
		

	def get_context_data(self,**kwargs):
		# raise Exception('hello')
		context = super( **kwargs).get_context_data()
		context['object'] = self.request.user
		return context

accounts/templates/accounts/dashboard.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}

<div class="section container">
<h4><blockquote class="green-text">{{object|title}}</blockquote></h4>
<div class="row center">
<div class="col l9 m9 s12">
	<table class="bordered striped centered ">
	{% for key, val in object.attrs %}
	
	<tr>
	<th>{{key}}</th>
	<td >{{val|truncatechars:50}}</td>
	</tr>
	{% endfor %}
	</table>
<hr>
</div>

<div class="col l3 m3 s12 ">
	<table class="bordered striped centered ">
	<tr><thead><th> Songs</th></thead></tr>
	<tbody>
	{% for song in object.song_set.all %}
		<tr><td> <a href="{% url 'Music:music' curr=song.pk %}">{{song | truncatechars:25}}</a></td></tr>
	{% endfor %}
	
	</table>
</div>

</div>
</div>
<br><br>



{%endblock%}

accounts/templates/accounts/signup.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}

<div class="row container valign-wrapper" style="margin-top:5%;">
<div class="col m4 l4 s12">

<h3><blockquote class="green-text">Sign Up</blockquote></h3>
</div>

<div class="col m8 l8 s12">

<form method="POST" action = "{% url 'accounts:signup' %}?next={{next}}">
{% csrf_token %}
{{form.as_p}}

  <button class="btn blue darken-4 waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
        
</form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends "includes/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block maincontent %}

<div class="section container">
<h4><blockquote class="green-text">{{object|title}}</blockquote></h4>
<div class="row center">
<div class="col l9 m9 s12">
	<table class="bordered striped centered ">
	{% for key, val in object.attrs %}
	
	<tr>
	<th>{{key}}</th>
	<td >{{val|truncatechars:50}}</td>
	</tr>
	{% endfor %}
	</table>
<hr>
</div>

<div class="col l3 m3 s12 ">
	<table class="bordered striped centered ">
	<tr><thead><th> Songs</th></thead></tr>
	<tbody>
	{% for song in object.song_set.all %}
		<tr><td> <a href="{% url 'Music:music' curr=song.pk %}">{{song | truncatechars:25}}</a></td></tr>
	{% endfor %}
	
	</table>
</div>

</div>
</div>
<br><br>



{%endblock%}