Music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from Music.views import *

app_name='Music'

urlpatterns = [
    url(r'^$', SongsList.as_view(), name='music'),
    url(r'^(?P<curr>[0-9]*)$', SongsList.as_view(), name='music'),
    url(r'^update/', updateSongs, name='updateSongs'),
    url(r'^record/$', record, name='record'),
    url(r'^add/$', AddSong, name='add'),  # needs improvement
    # url(r'^test/$', test, name='test'),  # needs improvement
    # url(r'^test/$', cfList ,name='test'),

]

RecSys/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls ),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^Music/', include('Music.urls')),
    url(r'^$', index, name='index'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT}))

accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import LoginView,LogoutView
from .views import SignUp, ProfileView, LoginView, LogoutView, DashboardView
from django.contrib.auth.decorators import login_required

app_name='accounts'
urlpatterns = [
    url(r'^signup/$',SignUp.as_view(),name='signup'),
    url(r'^profile/(?P<pk>\d+)$',ProfileView.as_view(),name='profile'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$',login_required(DashboardView.as_view()),name='dashboard'),

]

templates/includes/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>


{% load static %}
<!-- favicon Icon for the site -->
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css"> -->
<link rel="stylesheet" type="text/css" href="{% static 'css/materialize.min.css' %}" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" /> -->

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script> -->
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>


<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body >

<div id="progress_bar_container">
  <div class="progress">
      <div class="indeterminate"></div>
  </div>
</div>

<style>
  #progress_bar_container{
    background:#eee;
    position:fixed;
    width:100%;
    height:100%;
  }
  #progress_bar_container .progress{
    position:relative;
    width:40%;
    top:40%;
    left:30%;
  }
</style>
<script>
$(document).ready(function(){
    // alert("loaded");
$('#progress_bar_container').fadeOut(100);
});
</script>
    {% block menu %}
    {% include "includes/menu.html" %}
    {% endblock %}
    
    {% block content %}
    {% block sidenav %}
    {% endblock %}
    {% block maincontent %}
    {% endblock %}
    {% endblock %}

    {% block footer %}
<!-- 
        <footer class="page-footer black" style="position:ablolute;bottom:0px;width:100%;">
          
          <div class="footer-copyright">
            <div class="container" style="text-align: center;">
            <div class="right">Made by <b>Anurag : B15CS041</b>
            </div>
            </div>
          </div>
        </footer>
 -->
    
    {% endblock %}


<!-- Required JS files -->
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/includes/menu.html
{% block menu %}

{% if request.user.is_authenticated %}
	<!-- <div class="navbar-fixed"> -->
	<!-- Using both Navbar-fixed and side-nav causes unexpected results  -->
	<nav >
	<div class="nav-wrapper blue darken-4">
	  <a href="{% url 'index' %}" class="brand-logo center">RecSys</a>
	  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      
	  <ul id="nav-mobile" class="right hide-on-med-and-down">
	    {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
	    <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
	    <li><a href="{% url 'accounts:profile' request.user.pk %}">Profile</a></li>
	    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
	  </ul>
	  <ul id="nav-mobile" class="left hide-on-med-and-down">
	    <li><a href="{% url 'Music:music' %}">Music</a></li>
	  </ul>

	  <ul class="side-nav" id="mobile-demo">
        {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
		<li><a href="{% url 'Music:music' %}">Music</a></li>
  	    <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
	    <li><a href="{% url 'accounts:profile' request.user.pk %}">Profile</a></li>
	    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      </ul>
	</div>
	</nav>
	<!-- </div> -->
{% else %}
	<!-- <div class="navbar-fixed"> -->
	<nav >
	<div class="nav-wrapper blue darken-4">
	  <a href="{% url 'index' %}" class="brand-logo center">RecSys</a>
	  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
	  <ul id="nav-mobile" class="right hide-on-med-and-down">
	    <li><a href="{% url 'accounts:login' %}">Login</a></li>
	    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
	  </ul>
	  <ul id="nav-mobile" class="left hide-on-med-and-down">
	    <li><a href="{% url 'Music:music' %}">Music</a></li>
	  </ul>

	  <ul class="side-nav" id="mobile-demo">
		<li><a href="{% url 'Music:music' %}">Music</a></li>
	  	<li><a href="{% url 'accounts:login' %}">Login</a></li>
	    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
      </ul>
	</div>
	</nav>
	<!-- </div> -->
{% endif %}	
 
{% endblock %}